/*
 * Copyright (c) 2019 David Castañón <antik10ud@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * This class file was automatically generated by jASN1 v1.6.0 (http://www.openmuc.org)
 */

package com.k10ud.asn1.x509_certificate;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.math.BigInteger;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class AAControls  implements Encodedable,Decodeable,SourcePostitionable /*3*/{

public static final BerIdentifier identifier = new BerIdentifier(BerIdentifier.UNIVERSAL_CLASS, BerIdentifier.CONSTRUCTED, 16);
protected BerIdentifier id;

public byte[] code = null; public long from,to;
public BerInteger pathLenConstraint = null;

public AttrSpec permittedAttrs = null;

public AttrSpec excludedAttrs = null;

public BerBoolean permitUnSpecified = null;

public AAControls() {
id = identifier;
}

public AAControls(byte[] code) {
id = identifier;
this.code = code;
}

public AAControls(BerInteger pathLenConstraint, AttrSpec permittedAttrs, AttrSpec excludedAttrs, BerBoolean permitUnSpecified) {
id = identifier;
this.pathLenConstraint = pathLenConstraint;
this.permittedAttrs = permittedAttrs;
this.excludedAttrs = excludedAttrs;
this.permitUnSpecified = permitUnSpecified;
}

public int encode(BerByteArrayOutputStream os, boolean explicit) throws IOException {

int codeLength;

if (code != null) {
codeLength = code.length;
for (int i = code.length - 1; i >= 0; i--) {
os.write(code[i]);
}
}
else {
codeLength = 0;
if (permitUnSpecified != null) {
codeLength += permitUnSpecified.encode(os, true);
}

if (excludedAttrs != null) {
codeLength += excludedAttrs.encode(os, false);
// write tag: CONTEXT_CLASS, CONSTRUCTED, 1
os.write(0xa1);
codeLength += 1;
}

if (permittedAttrs != null) {
codeLength += permittedAttrs.encode(os, false);
// write tag: CONTEXT_CLASS, CONSTRUCTED, 0
os.write(0xa0);
codeLength += 1;
}

if (pathLenConstraint != null) {
codeLength += pathLenConstraint.encode(os, true);
}

codeLength += BerLength.encodeLength(os, codeLength);
}

if (explicit) {
codeLength += id.encode(os);
}

return codeLength;
}

public int decode(long sourceOffset,byte[] bytes, boolean explicit) throws IOException {
return decode(new CountingInputStream(sourceOffset,new ByteArrayInputStream(bytes)), explicit);

}
public int decode(CountingInputStream is, boolean explicit) throws IOException {
int codeLength = 0;
this.from=is.getPosition();
int subCodeLength = 0;
BerIdentifier berIdentifier = new BerIdentifier();

if (explicit) {
codeLength += id.decodeAndCheck(is);
}

BerLength length = new BerLength();
codeLength += length.decode(is);

int totalLength = length.val;
codeLength += totalLength;

if (totalLength == 0) {
this.to=is.getPosition();
return codeLength;
}
subCodeLength += berIdentifier.decode(is);
if (berIdentifier.equals(BerInteger.identifier)) {
pathLenConstraint = new BerInteger();
subCodeLength += pathLenConstraint.decode(is, false);
if (subCodeLength == totalLength) {
this.to=is.getPosition();
return codeLength;
}
subCodeLength += berIdentifier.decode(is);
}

if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.CONSTRUCTED, 0)) {
permittedAttrs = new AttrSpec();
subCodeLength += permittedAttrs.decode(is, false);
if (subCodeLength == totalLength) {
this.to=is.getPosition();
return codeLength;
}
subCodeLength += berIdentifier.decode(is);
}

if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.CONSTRUCTED, 1)) {
excludedAttrs = new AttrSpec();
subCodeLength += excludedAttrs.decode(is, false);
if (subCodeLength == totalLength) {
this.to=is.getPosition();
return codeLength;
}
subCodeLength += berIdentifier.decode(is);
}

if (berIdentifier.equals(BerBoolean.identifier)) {
permitUnSpecified = new BerBoolean();
subCodeLength += permitUnSpecified.decode(is, false);
if (subCodeLength == totalLength) {
this.to=is.getPosition();
return codeLength;
}
}
throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);


}

public void encodeAndSave(int encodingSizeGuess) throws IOException {
BerByteArrayOutputStream os = new BerByteArrayOutputStream(encodingSizeGuess);
encode(os, false);
code = os.getArray();
}

public String toString() {
StringBuilder sb = new StringBuilder("SEQUENCE{");
boolean firstSelectedElement = true;
if (pathLenConstraint != null) {
sb.append("pathLenConstraint: ").append(pathLenConstraint);
firstSelectedElement = false;
}

if (permittedAttrs != null) {
if (!firstSelectedElement) {
sb.append(", ");
}
sb.append("permittedAttrs: ").append(permittedAttrs);
firstSelectedElement = false;
}

if (excludedAttrs != null) {
if (!firstSelectedElement) {
sb.append(", ");
}
sb.append("excludedAttrs: ").append(excludedAttrs);
firstSelectedElement = false;
}

if (permitUnSpecified != null) {
if (!firstSelectedElement) {
sb.append(", ");
}
sb.append("permitUnSpecified: ").append(permitUnSpecified);
firstSelectedElement = false;
}

sb.append("}");
return sb.toString();
}

@Override

 public long getFrom() {

     return from;

}

@Override

public long getTo() {

    return to;

}

}

