/*
 * Copyright (c) 2019 David Castañón <antik10ud@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * This class file was automatically generated by jASN1 v1.6.0 (http://www.openmuc.org)
 */

package com.k10ud.asn1.x509_certificate;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.math.BigInteger;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class TSTInfo  implements Encodedable,Decodeable,SourcePostitionable /*3*/{

public static final BerIdentifier identifier = new BerIdentifier(BerIdentifier.UNIVERSAL_CLASS, BerIdentifier.CONSTRUCTED, 16);
protected BerIdentifier id;

public byte[] code = null; public long from,to;
public BerInteger version = null;

public TSAPolicyId policy = null;

public MessageImprint messageImprint = null;

public BerInteger serialNumber = null;

public BerGeneralizedTime genTime = null;

public Accuracy accuracy = null;

public BerBoolean ordering = null;

public BerInteger nonce = null;

public GeneralName tsa = null;

public Extensions extensions = null;

public TSTInfo() {
id = identifier;
}

public TSTInfo(byte[] code) {
id = identifier;
this.code = code;
}

public TSTInfo(BerInteger version, TSAPolicyId policy, MessageImprint messageImprint, BerInteger serialNumber, BerGeneralizedTime genTime, Accuracy accuracy, BerBoolean ordering, BerInteger nonce, GeneralName tsa, Extensions extensions) {
id = identifier;
this.version = version;
this.policy = policy;
this.messageImprint = messageImprint;
this.serialNumber = serialNumber;
this.genTime = genTime;
this.accuracy = accuracy;
this.ordering = ordering;
this.nonce = nonce;
this.tsa = tsa;
this.extensions = extensions;
}

public int encode(BerByteArrayOutputStream os, boolean explicit) throws IOException {

int codeLength;

if (code != null) {
codeLength = code.length;
for (int i = code.length - 1; i >= 0; i--) {
os.write(code[i]);
}
}
else {
codeLength = 0;
int sublength;

if (extensions != null) {
codeLength += extensions.encode(os, false);
// write tag: CONTEXT_CLASS, CONSTRUCTED, 1
os.write(0xa1);
codeLength += 1;
}

if (tsa != null) {
sublength = tsa.encode(os, true);
codeLength += sublength;
codeLength += BerLength.encodeLength(os, sublength);
// write tag: CONTEXT_CLASS, CONSTRUCTED, 0
os.write(0xa0);
codeLength += 1;
}

if (nonce != null) {
codeLength += nonce.encode(os, true);
}

if (ordering != null) {
codeLength += ordering.encode(os, true);
}

if (accuracy != null) {
codeLength += accuracy.encode(os, true);
}

codeLength += genTime.encode(os, true);

codeLength += serialNumber.encode(os, true);

codeLength += messageImprint.encode(os, true);

codeLength += policy.encode(os, true);

codeLength += version.encode(os, true);

codeLength += BerLength.encodeLength(os, codeLength);
}

if (explicit) {
codeLength += id.encode(os);
}

return codeLength;
}

public int decode(long sourceOffset,byte[] bytes, boolean explicit) throws IOException {
return decode(new CountingInputStream(sourceOffset,new ByteArrayInputStream(bytes)), explicit);

}
public int decode(CountingInputStream is, boolean explicit) throws IOException {
int codeLength = 0;
this.from=is.getPosition();
int subCodeLength = 0;
BerIdentifier berIdentifier = new BerIdentifier();

if (explicit) {
codeLength += id.decodeAndCheck(is);
}

BerLength length = new BerLength();
codeLength += length.decode(is);

int totalLength = length.val;
codeLength += totalLength;

subCodeLength += berIdentifier.decode(is);
if (berIdentifier.equals(BerInteger.identifier)) {
version = new BerInteger();
subCodeLength += version.decode(is, false);
subCodeLength += berIdentifier.decode(is);
}
else {
throw new IOException("Identifier does not match the mandatory sequence element identifer.");
}

if (berIdentifier.equals(TSAPolicyId.identifier)) {
policy = new TSAPolicyId();
subCodeLength += policy.decode(is, false);
subCodeLength += berIdentifier.decode(is);
}
else {
throw new IOException("Identifier does not match the mandatory sequence element identifer.");
}

if (berIdentifier.equals(MessageImprint.identifier)) {
messageImprint = new MessageImprint();
subCodeLength += messageImprint.decode(is, false);
subCodeLength += berIdentifier.decode(is);
}
else {
throw new IOException("Identifier does not match the mandatory sequence element identifer.");
}

if (berIdentifier.equals(BerInteger.identifier)) {
serialNumber = new BerInteger();
subCodeLength += serialNumber.decode(is, false);
subCodeLength += berIdentifier.decode(is);
}
else {
throw new IOException("Identifier does not match the mandatory sequence element identifer.");
}

if (berIdentifier.equals(BerGeneralizedTime.identifier)) {
genTime = new BerGeneralizedTime();
subCodeLength += genTime.decode(is, false);
if (subCodeLength == totalLength) {
this.to=is.getPosition();
return codeLength;
}
subCodeLength += berIdentifier.decode(is);
}
else {
throw new IOException("Identifier does not match the mandatory sequence element identifer.");
}

if (berIdentifier.equals(Accuracy.identifier)) {
accuracy = new Accuracy();
subCodeLength += accuracy.decode(is, false);
if (subCodeLength == totalLength) {
this.to=is.getPosition();
return codeLength;
}
subCodeLength += berIdentifier.decode(is);
}

if (berIdentifier.equals(BerBoolean.identifier)) {
ordering = new BerBoolean();
subCodeLength += ordering.decode(is, false);
if (subCodeLength == totalLength) {
this.to=is.getPosition();
return codeLength;
}
subCodeLength += berIdentifier.decode(is);
}

if (berIdentifier.equals(BerInteger.identifier)) {
nonce = new BerInteger();
subCodeLength += nonce.decode(is, false);
if (subCodeLength == totalLength) {
this.to=is.getPosition();
return codeLength;
}
subCodeLength += berIdentifier.decode(is);
}

if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.CONSTRUCTED, 0)) {
subCodeLength += length.decode(is);
tsa = new GeneralName();
subCodeLength += tsa.decode(is, null);
if (subCodeLength == totalLength) {
this.to=is.getPosition();
return codeLength;
}
subCodeLength += berIdentifier.decode(is);
}

if (berIdentifier.equals(BerIdentifier.CONTEXT_CLASS, BerIdentifier.CONSTRUCTED, 1)) {
extensions = new Extensions();
subCodeLength += extensions.decode(is, false);
if (subCodeLength == totalLength) {
this.to=is.getPosition();
return codeLength;
}
}
throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);


}

public void encodeAndSave(int encodingSizeGuess) throws IOException {
BerByteArrayOutputStream os = new BerByteArrayOutputStream(encodingSizeGuess);
encode(os, false);
code = os.getArray();
}

public String toString() {
StringBuilder sb = new StringBuilder("SEQUENCE{");
sb.append("version: ").append(version);

sb.append(", ");
sb.append("policy: ").append(policy);

sb.append(", ");
sb.append("messageImprint: ").append(messageImprint);

sb.append(", ");
sb.append("serialNumber: ").append(serialNumber);

sb.append(", ");
sb.append("genTime: ").append(genTime);

if (accuracy != null) {
sb.append(", ");
sb.append("accuracy: ").append(accuracy);
}

if (ordering != null) {
sb.append(", ");
sb.append("ordering: ").append(ordering);
}

if (nonce != null) {
sb.append(", ");
sb.append("nonce: ").append(nonce);
}

if (tsa != null) {
sb.append(", ");
sb.append("tsa: ").append(tsa);
}

if (extensions != null) {
sb.append(", ");
sb.append("extensions: ").append(extensions);
}

sb.append("}");
return sb.toString();
}

@Override

 public long getFrom() {

     return from;

}

@Override

public long getTo() {

    return to;

}

}

